### ISSUE TITLE
ErrorException in POST /api/visits/punch

### ISSUE THREAD

**Issue by georgeburdell** [RoboJackets/people-counter#273]
## Error in People Counter

**ErrorException** in **POST /api/visits/punch**
Trying to get property 'children' of non-object

[View on Bugsnag](https://app.bugsnag.com/robojackets/people-counter/errors/604c0715ea012c0007062978?event_id=604c07820073b56a71d10000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/VisitPunchController.php:115 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    app/Http/Controllers/VisitPunchController.php:115 - App\Http\Controllers\VisitPunchController::store

[View full stacktrace](https://app.bugsnag.com/robojackets/people-counter/errors/604c0715ea012c0007062978?event_id=604c07820073b56a71d10000&i=gh&m=ci)

*Created by RoboJackets Admin via Bugsnag*

**Comment by kberzinch** [comment]
This was from a web punch out request that only had gtid and door fields.
